### ISSUE TITLE
[1.12.2] Crashes on Server

### ISSUE THREAD

**Issue by KAfable** [MattCzyr/Notes#11]
Is it possible to add a check for the mod if its on clientside or serverside?

**Comment by Poslovitch** [comment]
https://github.com/MattCzyr/Notes/blob/master/src/main/java/com/chaosthedude/notes/Notes.java#L16
```java
@Mod(modid = Notes.MODID, name = Notes.NAME, version = Notes.VERSION, acceptedMinecraftVersions = "[1.12]", clientSideOnly = true)
```

The mod explicitly tells it is client side only.

Do you have an error report, or logs to show us?

**Comment by robmart** [comment]
@Poslovitch While it is set to client-side only here on Github, it is not on Curse. The latest version was uploaded one month before that commit was pushed.
