### ISSUE TITLE
Mark as 1.12.2 Compatible On Curse

### ISSUE THREAD

**Issue by jarodsstuff** [MattCzyr/Notes#13]
Currently the mod is listed as 1.12 only (not 1.12.1 or 1.12.2) on Curse, but it works in my singleplayer world on 1.12.2. Please mark it as 1.12.2 compatible so others and I do not have to install it manually if using the Twitch Launcher.

**Comment by mrdeadlocked** [comment]
This would be great!

**Comment by MattCzyr** [comment]
Finally got around to marking it as 1.12.1 and 1.12.2 compatible. Thanks
