### ISSUE TITLE
#11 Extended - Server/Client not compatible

### ISSUE THREAD

**Issue by X-Niter** [MattCzyr/Notes#17]
This slightly adds to #11 however I already knew this was client-side. 
The issue however is a client-to-server compatibility ping whenever you look in the multiplayer list. 

I had notes on my modpack and the server did not, the issue is that note is causing the server ping to state that the pack is not compatible and showing the big red X. 
I can still connect to the server even though the red X on the ping says it's incompatible.
Is this incompatibility ping issue something that can be resolved on your mod? 
You are not the only mod causing this to happen but still being able to connect, ITLT is doing something just the same.

**Comment by MattCzyr** [comment]
Good catch, should be fixed in version 1.2.3.
