### ISSUE TITLE
Crash When Trying To Highlight Text

### ISSUE THREAD

**Issue by JaRyCu** [MattCzyr/Notes#2]
Pastebin: http://pastebin.com/YyeCAeaw

I was playing SF3 tonight and recording an episode for my LP using Mirilis Action!  My plan was to show off the Notes mod because I absolutely love it, and everything was going well.  This is actually the 2nd episode I've shown it off in today, using the 1.7.10 for PO2 Kappa Mode earlier with no issues.

Well tonight, I went to highlight a line of text by clicking at the end and then hitting shift+home and the game froze for 3-5 seconds and then the entire client crashed.  I posted the error report to pastebin and linked it above so that you can look at it.

In addition to the standard SF3 mods, I've added MouseTweaks, CraftingTweaks, and your mod.  My instance is a single player world, no servers involved.

**Comment by MattCzyr** [comment]
Seems to be an issue solely on my end, just something I overlooked. I'll get that sorted out tonight.

**Comment by JaRyCu** [comment]
While you're fixing that, I'd like to make a suggestion.  I've noticed I can't <TAB> from the Title box to the actual Notes box.  I'm old school and learned to use computers before the mouse was commonplace (1980s) and I'm just used to tabbing through boxes.  Would that be hard to add or a feature that'd be worth adding?

**Comment by MattCzyr** [comment]
That's a feature I had in the back of my head but forgot to add before the initial release. It'll make its way into the next update.

**Comment by MattCzyr** [comment]
Fix will be released in version 1.1.0 later today.
