### ISSUE TITLE
dateFormat in config showing day of year instead of day of month with leading zero when DD is used

### ISSUE THREAD

**Issue by VeraSimon** [MattCzyr/Notes#23]
Notes Version: Notes-1.16.5-1.2.3
Forge version: 1.16.5 - 36.2.2
Minecraft version: 1.16.5

As far as I can tell, the date format in the config is using ISO 8601 for its rules, but when I use 'DD' to show the day of the month with a leading zero, it shows the day of the year, which is what I'd expect from 'DDD'. 

You can reproduce this by using the dateFormat string 'YYYY-MM-DD_HH:mm:ssZZ', then running the game and looking at the Last Modified value on existing or new notes.

**Comment by MattCzyr** [comment]
This is an old issue, but commenting just for future reference:

Date formats use Java's [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) conventions. In this spec, `D` is day in year and `d` is day in month. To show day in month with a leading zero, use `dd`.
