### ISSUE TITLE
Can't Open GUI

### ISSUE THREAD

**Issue by mandychuu** [MattCzyr/Notes#25]
The default keystroke for opening the Notes GUI was already bound to another mod, so I tried several different available ones. I'm sensing that there's most likely a conflicting mod causing it to not respond, but I'm not sure what it could be?

I don't have a crash log since my game has been stable.

**Comment by MattCzyr** [comment]
What version are you using?

**Comment by mandychuu** [comment]
If you're asking about Minecraft, default 1.19 on a Forge 41.0.92 server via Apex. I'd upgrade to the latest Forge, but some of our other mods have trouble working on anything higher as of current. I'm also using the full release 1.19 Optifine.

And if you're asking about the mod itself, I was trying to use 1.19-1.2.4.

**Comment by MattCzyr** [comment]
Haven't been able to recreate this one myself, but try this beta version and see if the issue persists:

https://www.dropbox.com/s/1gmfj85zw9tsbfu/Notes-1.19-1.2.5-beta.jar?dl=0
