### ISSUE TITLE
[Request] Fabric version

### ISSUE THREAD

**Issue by ivanruvalcaba** [MattCzyr/Notes#26]
Nice day!

Your mod is awesome, any chance to offer a version for fabric? The fabric port looks like it will no longer be updated.

https://www.curseforge.com/minecraft/mc-mods/notes-fabric?comment=86

> […] I don't have the code anymore […]

Best regards.

**Comment by KajeArch** [comment]
Seconded. This definitely needs a Fabric version.

**Comment by MattCzyr** [comment]
Just released a version on CurseForge for Fabric 1.19.2.
