### ISSUE TITLE
1.11.2 UI unresponsive when accessed with MineMenu

### ISSUE THREAD

**Issue by crysthala** [MattCzyr/Notes#4]
I'm putting together a personal modpack that includes a lot of utility-type-stuff, so there are lots of keybinds. I thought I'd use MineMenu instead of trying to remember them all. Unfortunately, Notes doesn't seem to like it very much.

Notes works perfectly (and is delightful) when I use a dedicated hotkey, but it doesn't respond when accessed through MineMenu's "press keybind" feature. The GUI comes up, but no amount of clicking or keymashing makes anything happen. I can't close the GUI, either, so I end up having to exit the game.

Minecraft 1.11.2, Forge 13.20.0.2282, Notes 1.1.0, and [MineMenu 1.5.0](https://minecraft.curseforge.com/projects/minemenu). Log doesn't show anything I recognize as an error, but here it is anyway for due diligence: [latest.txt](https://github.com/MattCzyr/Notes/files/920701/latest.txt)

If there's nothing to be done, I understand completely, but it'd be great for them to play nice together. Thanks!

**Comment by MattCzyr** [comment]
Tested it myself and it works just fine when the shortcut is set up correctly. However, when I set the keybind to toggle instead of press, the GUI becomes unresponsive. Make sure the shortcut is set to press and not toggle.

**Comment by crysthala** [comment]
Ah. Yep, that was it! I must have hit that button on accident. Derp. Thanks for your help, and for a stupendously useful mod.
